application:
  host: "0.0.0.0"
  log_level: "zero2prod=debug,sqlx=debug,tower_http=debug,axum::rejection=debug"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "newsletter@tzatziki.world"
